"""Add user settings

Revision ID: 20f76eea4bd8
Revises: 7ee52d4b4c6e
Create Date: 2026-08-16 22:40:13.074543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20f76eea4bd8'
down_revision = '7ee52d4b4c6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=False),
    sa.Column('breakfast_enabled', sa.Boolean(), nullable=False),
    sa.Column('breakfast_time', sa.String(length=5), nullable=False),
    sa.Column('lunch_enabled', sa.Boolean(), nullable=False),
    sa.Column('lunch_time', sa.String(length=5), nullable=False),
    sa.Column('dinner_enabled', sa.Boolean(), nullable=False),
    sa.Column('dinner_time', sa.String(length=5), nullable=False),
    sa.Column('weekly_progress_enabled', sa.Boolean(), nullable=False),
    sa.Column('recommendation_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_settings')
    # ### end Alembic commands ###
