"""Make user profile one-to-one

Revision ID: 29a21c9c6d69
Revises: 106f3ce1fd33
Create Date: 2026-08-16 10:55:19.571585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29a21c9c6d69'
down_revision = '106f3ce1fd33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edible_portion', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('moisture', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('carbohydrate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('minerals', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('energy', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('phosphorus', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('carotene', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('thiamine', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('riboflavin', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('niacin', sa.Float(), nullable=True))
        batch_op.drop_column('carbs')
        batch_op.drop_column('food_name_nepali')
        batch_op.drop_column('potassium')
        batch_op.drop_column('vitamin_a')
        batch_op.drop_column('calories')
        batch_op.drop_column('sodium')
        batch_op.drop_column('category')

    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('sodium', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('calories', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('vitamin_a', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('potassium', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('food_name_nepali', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('carbs', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.drop_column('niacin')
        batch_op.drop_column('riboflavin')
        batch_op.drop_column('thiamine')
        batch_op.drop_column('carotene')
        batch_op.drop_column('phosphorus')
        batch_op.drop_column('energy')
        batch_op.drop_column('minerals')
        batch_op.drop_column('carbohydrate')
        batch_op.drop_column('moisture')
        batch_op.drop_column('edible_portion')

    # ### end Alembic commands ###
