"""Update food model for meal clusters

Revision ID: 4687b002d251
Revises: e4ef0512c918
Create Date: 2026-08-17 13:14:02.494923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4687b002d251'
down_revision = 'e4ef0512c918'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('foods_sn_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('foods_sn_key'), ['sn'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
