"""Add nutrition snapshot to meal plan items

Revision ID: 552934ea6e59
Revises: 94b09f38d014
Create Date: 2026-08-17 22:25:46.568409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '552934ea6e59'
down_revision = '94b09f38d014'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal_plan_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calories', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('protein', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('fat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('carbs', sa.Float(), nullable=True))
        batch_op.alter_column('meal_type',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.alter_column('serving_size',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal_plan_items', schema=None) as batch_op:
        batch_op.alter_column('serving_size',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('meal_type',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
        batch_op.drop_column('carbs')
        batch_op.drop_column('fat')
        batch_op.drop_column('protein')
        batch_op.drop_column('calories')

    # ### end Alembic commands ###
