"""Food selection

Revision ID: 58edf8adba69
Revises: 552934ea6e59
Create Date: 2026-08-18 14:33:00.463164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58edf8adba69'
down_revision = '552934ea6e59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_of_birth', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_column('date_of_birth')

    # ### end Alembic commands ###
