"""Add recommendation and food intake logs

Revision ID: 7ee52d4b4c6e
Revises: 29a21c9c6d69
Create Date: 2026-08-16 21:33:09.457413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ee52d4b4c6e'
down_revision = '29a21c9c6d69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_intake_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('quantity_g', sa.Float(), nullable=False),
    sa.Column('meal_type', sa.String(length=30), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('food_intake_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_food_intake_logs_consumed_at'), ['consumed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_food_intake_logs_user_id'), ['user_id'], unique=False)

    op.create_table('recommendation_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target_calories', sa.Float(), nullable=True),
    sa.Column('goal', sa.String(length=50), nullable=True),
    sa.Column('cluster_id', sa.Integer(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recommendation_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommendation_logs_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommendation_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendation_logs_user_id'))

    op.drop_table('recommendation_logs')
    with op.batch_alter_table('food_intake_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_food_intake_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_food_intake_logs_consumed_at'))

    op.drop_table('food_intake_logs')
    # ### end Alembic commands ###
