"""Update food model for meal categories and clustering

Revision ID: e4ef0512c918
Revises: e207767f1868
Create Date: 2026-08-17 13:06:36.886101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4ef0512c918'
down_revision = 'e207767f1868'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sn', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('food_name_clean', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('carbs', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('calories', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('breakfast', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('lunch', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('dinner', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('breakfast_cluster', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('lunch_cluster', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('dinner_cluster', sa.Integer(), nullable=True))
        batch_op.alter_column('food_name',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['sn'])
        batch_op.drop_column('cluster_id')
        batch_op.drop_column('carotene')
        batch_op.drop_column('phosphorus')
        batch_op.drop_column('edible_portion')
        batch_op.drop_column('thiamine')
        batch_op.drop_column('moisture')
        batch_op.drop_column('niacin')
        batch_op.drop_column('riboflavin')
        batch_op.drop_column('minerals')
        batch_op.drop_column('energy')
        batch_op.drop_column('carbohydrate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('carbohydrate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('energy', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('minerals', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('riboflavin', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('niacin', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('moisture', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('thiamine', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('edible_portion', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('phosphorus', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('carotene', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cluster_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('food_name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
        batch_op.drop_column('dinner_cluster')
        batch_op.drop_column('lunch_cluster')
        batch_op.drop_column('breakfast_cluster')
        batch_op.drop_column('dinner')
        batch_op.drop_column('lunch')
        batch_op.drop_column('breakfast')
        batch_op.drop_column('calories')
        batch_op.drop_column('carbs')
        batch_op.drop_column('food_name_clean')
        batch_op.drop_column('sn')

    # ### end Alembic commands ###
